openapi: '3.0.2'
info:
  title: REST Starter Kit
  description: This is a starter kit that can be used to create microservice
  version: '1.0.0'
  
servers:
  - url: https://localhost/starterkit/v1
    description: localhost

paths:
  /otpcount/{operationType}:
    get:
      tags:
        - OTP
      description: Checks the otp send and validate counters
      operationId: controllers.rnd.get_otp_count
      parameters:
        - in: path
          name: operationType 
          description: The operation type
          required: true
          schema:
            type: string
            example: SendOTP
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/otp_response'


  /random:
    get:
      tags:
        - random
      description: Generates a random number
      operationId: controllers.rnd.generate_random_number
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/random'

  /greetings/{word}:
    get:
      tags:
        - greetings
      description: Get information about the given word
      operationId: controllers.word_controller.get_word
      parameters:
        - in: path
          name: word
          description: Give me some word, I want to learn
          required: true
          schema:
            type: string
          example: 'One'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/word-message'
        '201':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/word-message'

components:
  schemas:

    random:
      type: object
      properties:
        number:
          type: integer
          description: The random generated number
          example: 7

    word-message:
      type: object
      properties:
        input:
          type: string
          description: Word entered by user
          example: 201301
        message:
          type: string
          description: Message from computer
          example: 'Hi there how are you'
        word_count:
          type: integer
          description: No's of words that I have
          example: 46
          
    otp_response:
      type: object
      properties:
        count:
          type: string
          description: count of operation
          example: 2
        countRemaining:
          type: string
          description: count of operation remaining
          example: 0

